### ISSUE TITLE
Bug when setting the updated_at/by audit info

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/ixmp4#126]
When editing a Run (adding/removing iamc-data or meta), the updated_at/by audit info entries are updated automatically. However, this update touches **all runs** with that model-scenario name, not just the run that was edited.

Steps to reproduce (I guess only relevant via Rest API):
- login as user A
- create a run
- login as user B
- create a run with the same model/scenario name
 
The first run (created by user A) now has "updated_by user B" in the audit info.

**Comment by meksor** [comment]
fixed by #127
