### ISSUE TITLE
Install requires building `psycopg2` from source

### ISSUE THREAD

**Issue by danielhuppmann** [iiasa/ixmp4#20]
Per this discussion https://github.com/IAMconsortium/pyam/issues/783 raised by @khaeru, the current dependency on `psycopg2` and `pg_config` is too cumbersome for the wide user base reached via pyam and message-ix.

Therefore, Postgres should be turned into an optional dependency so that users can easily use the Rest-API-client-part of ixmp4.

**Comment by meksor** [comment]
Whoops seems we worked on that at the same time: 
Quoting from the other thread: 

> Actually, a correction on this: psycopg3 IS out, its just not called psycopg3 but reintegrated into the original package. Furthermore, binary installation is no longer discouraged: https://www.psycopg.org/psycopg3/docs/basic/install.html#binary-installation
There is also a pure-python implementation to fall back to but it still requires postgres system dependencies...
