### ISSUE TITLE
Issue release 0.5.1 for pydantic v2 update

### ISSUE THREAD

**Issue by phackstock** [iiasa/ixmp4#36]
I am currently in the process of updating nomenclature to use pydantic 2.
Since pydantic update is not currently in the latest pypi version of ixmp4 I cannot update nomenclature. 
A quick release 0.5.1 would fix this and be much appreciated.
@danielhuppmann, would you have any objections?

**Comment by danielhuppmann** [comment]
How about we wait until Thursday, maybe I can get the meta-tables to work, and then we have a ixmp4 release 0.6?

**Comment by danielhuppmann** [comment]
Completed via release v0.6
