### ISSUE TITLE
Version 0.7.0 breaks pyam test

### ISSUE THREAD

**Issue by phackstock** [iiasa/ixmp4#50]
As I was working on pyam yesterday (IAMconsortium/pyam#818) I noticed that `ixmp4 0.7.0` broke the test `test_ixmp4_integration[test_df0]` from `tests/test_ixmp4.py` (https://github.com/IAMconsortium/pyam/actions/runs/8067457546/job/22037916444) with the following error:
 
```console
...
pyarrow/error.pxi:154: in pyarrow.lib.pyarrow_internal_check_status
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   pyarrow.lib.ArrowNotImplementedError: Function 'not_equal' has no kernel matching input types (string, double)

pyarrow/error.pxi:91: ArrowNotImplementedError
```

looks like it's got something to do with `pyarrow`.
Reverting to ixmp4 version 0.6.0 fixed the test.
Just talked to @meksor and he said that you, @glatterf42, would be the best person to take a look.

FYI @danielhuppmann.

**Comment by glatterf42** [comment]
I'm not sure this is ixmp4's fault. My interpretation is that
```python
/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/ixmp4/data/db/meta/repository.py:194: in bulk_upsert
    super().bulk_upsert(type_df)
/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/ixmp4/data/db/base.py:376: in bulk_upsert
    self.bulk_upsert_chunk(df)
/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/ixmp4/data/db/base.py:394: in bulk_upsert_chunk
    cond.append(df[col] != df[updated_col])
```
and
```python
 E   pyarrow.lib.ArrowNotImplementedError: Function 'not_equal' has no kernel matching input types (string, double)

pyarrow/error.pxi:91: ArrowNotImplementedError
``` 
indicate that `df[col]` and `df[updated_col]` don't have compatible types. This could be on ixmp4 for trying to update the wrong column (which seems odd) or it could be on the pyam test setup for trying to pass an incompatible type. 
I'll have to install pyam and run the tests myself to inspect `test_df` more closely, I think.

**Comment by phackstock** [comment]
Thanks a lot for the detective work @glatterf42.

**Comment by danielhuppmann** [comment]
A dataframe like [this](https://github.com/IAMconsortium/pyam/blob/3d13de440175d9287015814f461bc8041c5118fa/tests/conftest.py#L54) converted to a dict like [this](https://github.com/IAMconsortium/pyam/blob/3d13de440175d9287015814f461bc8041c5118fa/pyam/ixmp4.py#L41).

**Comment by meksor** [comment]
Im running it locally with pandas 2.2.1 and the newest ixmp4 version...

**Comment by meksor** [comment]
Ok update, if I install pyarrow /alongside/ ixmp4, the tests in ixmp4 also fail... Seems pandas uses pyarrow if its available, breaking this test....

**Comment by meksor** [comment]
OK so pandas version 1.5.3 still works. Seems pandas version >2 will change its behaviour if pyarrow is installed. converting the columns to each other's types just yields another pyarrow error. 
I would suggest reverting the update to pandas 2, seems a bunch of stuff broke...

**Comment by danielhuppmann** [comment]
We bumped pyam to depend on pandas >= 2.0 a while ago to take advantage of the fast speed and improved API, so pinning ixmp4<2 isn't really an option...

**Comment by glatterf42** [comment]
It's happening in `df = self.merge_existing(df, existing_df)` already, which makes me think this could be related to dask instead of pandas.

https://github.com/dask/dask/issues/10631 might be related.

**Comment by meksor** [comment]
fixed with https://github.com/iiasa/ixmp4/releases/tag/v0.7.1
